theme = "nord-dark"
icons = "awesome"

[[block]]
block = "net"
device = "wlp1s0"
format = "{ssid} {signal_strength}"
interval = 5

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%a %I:%M %m/%d/%y"

[[block]]
block = "battery"
interval = 10
format = "{percentage:6#100} {percentage} {time}"
if_command = "test -e /sys/class/power_supply/BAT0"

